# Config File For CenterDet
work:
  proj_name: centerdet
  save_path: workspace
#  weights_path: # YOUR_MODEL_PATH
model:
  arch:
    name: OneStage
    backbone:
#      name: ResNet
#      depth: 18
      name: ShuffleNetV2
      model_size: 1.0x
      out_stages: [1, 2, 3, 4]
      kernal_size: 5
      activation: LeakyReLU
    neck:
      name: FPN
      out_channels: 96
  #    start_level: 0
  #    num_outs: 3
    head:
      name: TTFHead
      hm_head_planes: 48
      wh_head_planes: 48
      loc_weight: 1.
      reg_weight: 5.
  #    feat_channels: 64
      num_classes: 80
data:
  train:
    dataset:
      name: coco # label format
      img_path: coco/train2017
      ann_path: coco/annotations/instances_train2017.json
      input_size: [320, 320] # [w, h]
      keep_ratio: True
      pipeline:
        perspective: 0.0
        scale: [0.6, 1.4]
        stretch: [[1, 1], [1, 1]]
        rotation: 0
        shear: 0
        translate: 0.2
        flip: 0.5
        brightness: 0.2
        contrast: [0.8, 1.2]
        saturation: [0.8, 1.2]
        normalize: [[0, 0, 0], [255, 255, 255]]
        class_num: 80
        gt_type: ttfnet
    loader:
      shuffle: True
      pin_memory: True
      workers: 6
      batch_size: 96
      drop_last: False
      collate_fn: ttfnet

  val:
    name: coco
    img_path: coco/val2017
    ann_path: coco/annotations/instances_val2017.json
    input_size: [320, 320] # [w, h]
    keep_ratio: True
    pipeline:
      normalize: [[0, 0, 0], [255, 255, 255]]
      class_num: 80
      gt_type: ttfnet
#device:
#  gpu_ids: [0]
#  workers_per_gpu: 4
#  batchsize_per_gpu: 64
schedule:
  optimizer:
    name: SGD
    lr: 0.024
    momentum: 0.9
    weight_decay: 0.0001
  warmup:
    name: linear
    steps: 500
    ratio: 0.1
  total_epochs: 160
  lr_schedule:
    name: LambdaLR #MultiStepLR
    lr_final: 0.02
#    milestones: [130, 160, 150, 155]
#    gamma: 0.1
  val_intervals: 3
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP

class_names: ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus',
              'train', 'truck', 'boat', 'traffic_light', 'fire_hydrant',
              'stop_sign', 'parking_meter', 'bench', 'bird', 'cat', 'dog',
              'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe',
              'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee',
              'skis', 'snowboard', 'sports_ball', 'kite', 'baseball_bat',
              'baseball_glove', 'skateboard', 'surfboard', 'tennis_racket',
              'bottle', 'wine_glass', 'cup', 'fork', 'knife', 'spoon', 'bowl',
              'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot',
              'hot_dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
              'potted_plant', 'bed', 'dining_table', 'toilet', 'tv', 'laptop',
              'mouse', 'remote', 'keyboard', 'cell_phone', 'microwave',
              'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock',
              'vase', 'scissors', 'teddy_bear', 'hair_drier', 'toothbrush']